# Generated by Django 4.2.3 on 2024-03-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_remove_choice_correct_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='correct',
        ),
    ]
